# Generated by Django 5.0.1 on 2024-01-21 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apostilas', '0002_viewapostila'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewapostila',
            name='ip',
            field=models.GenericIPAddressField(default='127.0.0.1'),
        ),
    ]
